plugin de subastas
Ixogamer/ipxdevserver pull request #12
Opened 2021-07-07 18:17 UTC by chuske7

solo lo he configurado y traducido, el admin config esta a medio traducir pero porq me dijeron que no hacia falta y ya llevaba la mitad traducida espero que no importe

2021-07-07 23:56 UTC, Ixogamer commented
Está bien por lo que he visto, pero todavía no voy a mergear hasta que lo revise más a fondo

2021-07-08 01:44 UTC, Ixogamer requested changes
Hay que añadir la última versión del plugin, btw. https://www.spigotmc.org/resources/⚡-auctionmaster-2-⚡-1-8-1-17x-auctions-categories-bin-admin-view-fully-configurable.84784/updates

2021-07-08 02:29 UTC, Ixogamer requested changes
Cambiar "ofertador" a "pujador" y algunas "pujas" a "subastas". Esto lo hago yo en el próximo commit. Dejo la sugerencia para cuando me ponga a ello.

2021-07-08 02:52 UTC, Ixogamer requested changes
Por favor, no vuelvas a usar traductor para palabras solas :c, y pon primero los archivos de configuración en inglés, y luego en español (Para poder conseguir contexto)

2021-07-08 02:52 UTC, Ixogamer commented on plugins/AuctionMaster/auctions_manager.yml
> +    - '&7Mejor ofertador: %top-bid-player%'
```suggestion
    - '&7Mejor pujador: %top-bid-player%'
```

2021-07-08 02:52 UTC, Ixogamer commented on plugins/AuctionMaster/auctions_manager.yml
> +    - '&7Mejor oferta: &6%top-bid% monedas'
Quizás puja? Ah, y en vez de monedas, creo que ahí no debería haber nada, ya que el plugin de economía le debería añadir un Ξ (Símbolo de la economía de IpxCraft). Lo compruebo luego.

2021-07-08 02:52 UTC, Ixogamer commented on plugins/AuctionMaster/auctions_manager.yml
> +    - '&7Mejor ofertador: %top-bid-player%'
Lo mismo de líneas 27 y 28

2021-07-08 02:52 UTC, Ixogamer commented on plugins/AuctionMaster/auctions_manager.yml
> +    - '&7Estado: &aEnded!'
```suggestion
    - '&7Estado: &aAcabado!'
```

2021-07-08 02:52 UTC, Ixogamer commented on plugins/AuctionMaster/auctions_manager.yml
> +  lowest-bid: 'Oferta mas baja'
```suggestion
  highest-bid: 'Puja mas alta'
  lowest-bid: 'Puja mas baja'
```

2021-07-08 02:52 UTC, Ixogamer commented on plugins/AuctionMaster/auctions_manager.yml
> +  most-bids: 'Mayoría de las ofertas'
Creo que esto no está bien, pero no sé el contexto. Quizás debería ser
```suggestion
  most-bids: 'Más pujas'
```

2021-07-08 02:52 UTC, Ixogamer commented on plugins/AuctionMaster/auctions_manager.yml
> +manage-own-auctions-menu-name: '&8tu gestor de acciones'
¿Deberían de ser mayúsculas? Ah, y "auctions" es "subastas"
```suggestion
create-menu-name: '&8Creador de pujas'
manage-own-auctions-menu-name: '&8Tu gestor de subastas'
```

2021-07-08 02:52 UTC, Ixogamer commented on plugins/AuctionMaster/auctions_manager.yml
> +    - '&7pujas para otros jugadores'
```suggestion
    - '&7subastas para otros jugadores'
```

2021-07-08 02:52 UTC, Ixogamer commented on plugins/AuctionMaster/auctions_manager.yml
> +    - '&eClick para convertirte en rico!'
No sé si este contexto está bien, tengo que comprobarlo.

2021-07-08 02:52 UTC, Ixogamer commented on plugins/AuctionMaster/auctions_manager.yml
> +    - ''
Esto está mal traducido.

2021-07-08 02:52 UTC, Ixogamer commented on plugins/AuctionMaster/auctions_manager.yml
> +collect-all-message: '&aHas reclamado todas tus pujas!'
```suggestion
collect-all-message: '&aHas reclamado todas tus subastas!'
```

2021-07-08 02:52 UTC, Ixogamer commented on plugins/AuctionMaster/auctions_manager.yml
> +  no-item-selected-name: '&cCrear puja'
```suggestion
  no-item-selected-name: '&cCrear subasta'
```
creo?

2021-07-08 02:52 UTC, Ixogamer commented on plugins/AuctionMaster/auctions_manager.yml
> +    - '&7para esta puja.'
```suggestion
    - '&7para esta subasta.'
```

2021-07-08 02:52 UTC, Ixogamer commented on plugins/AuctionMaster/auctions_manager.yml
> +  item-selected-name: '&aCrear puja'
```suggestion
  item-selected-name: '&aCrear subasta'
```

2021-07-08 02:52 UTC, Ixogamer commented on plugins/AuctionMaster/auctions_manager.yml
> +    - '&7la casa de pujas para'
```suggestion
    - '&7la casa de subastas para'
```

2021-07-08 02:52 UTC, Ixogamer commented on plugins/AuctionMaster/auctions_manager.yml
> +    - '&7duracion de la puja: &e%duration%'
```suggestion
    - '&7Duración de la subasta: &e%duration%'
```

2021-07-08 02:52 UTC, Ixogamer commented on plugins/AuctionMaster/auctions_manager.yml
> +  - ''
Esto está algo mal traducido

2021-07-08 02:52 UTC, Ixogamer commented on plugins/AuctionMaster/auctions_manager.yml
> +  - '&7tiene hasta que se acaba la puja'
```suggestion
  - '&7tiene hasta que se acaba la subasta'
```

2021-07-08 02:52 UTC, Ixogamer commented on plugins/AuctionMaster/auctions_manager.yml
> +  - '&7Suplemento: &6+%starting-fee% monedas &e(5%)'
```suggestion
  - '&7Cuota: &6+%starting-fee% &e(5%)'
```
```suggestion
  - '&7Comisión: &6+%starting-fee% &e(5%)'
```

2021-07-08 02:52 UTC, Ixogamer commented on plugins/AuctionMaster/auctions_manager.yml
> +starting-bid-sign-deny: '&cEse numero no es valido.'
```suggestion
starting-bid-sign-deny: '&cEse número no es valido.'
```

2021-07-08 02:52 UTC, Ixogamer commented on plugins/AuctionMaster/auctions_manager.yml
> +seconds: 'Segundo'
```suggestion
seconds: 'Segundos'
```

2021-07-08 02:52 UTC, Ixogamer commented on plugins/AuctionMaster/auctions_manager.yml
> +day: 'Dia'
```suggestion
day: 'Día'
```

2021-07-08 02:52 UTC, Ixogamer commented on plugins/AuctionMaster/auctions_manager.yml
> +days: 'Dias'
```suggestion
days: 'Días'
```

2021-07-08 02:52 UTC, Ixogamer commented on plugins/AuctionMaster/auctions_manager.yml
> +extra-fee-message: '&7Suplemento: &6'
```suggestion
extra-fee-message: '&7Comisión: &6'
```

2021-07-08 02:52 UTC, Ixogamer commented on plugins/AuctionMaster/auctions_manager.yml
> +duration-menu-name: '&8Duracion de la puja'
```suggestion
duration-menu-name: '&8Duración de la puja'
```

2021-07-08 02:52 UTC, Ixogamer commented on plugins/AuctionMaster/auctions_manager.yml
> +  - '&7que sea la puja.'
```suggestion
  - '&7que sea la subasta.'
```

2021-07-08 02:52 UTC, Ixogamer commented on plugins/AuctionMaster/auctions_manager.yml
> +duration-sign-deny: '&cEse numero no es valido.'
```suggestion
duration-sign-deny: '&cEse número no es valido.'
```

2021-07-08 02:52 UTC, Ixogamer commented on plugins/AuctionMaster/auctions_manager.yml
> +not-enough-money-auction: '&cNo tienes suficiente dinero para crear esta puja.'
```suggestion
not-enough-money-auction: '&cNo tienes suficiente dinero para crear esta subasta.'
```

2021-07-08 02:52 UTC, Ixogamer commented on plugins/AuctionMaster/auctions_manager.yml
> +auction-confirm-menu-name: '&8Confirmar puja'
```suggestion
auction-confirm-menu-name: '&8Confirmar subasta'
```
(Creo)

2021-07-08 02:52 UTC, Ixogamer commented on plugins/AuctionMaster/auctions_manager.yml
> +  - '&7de la puja.'
```suggestion
  - '&7de la subasta.'
```

2021-07-08 02:52 UTC, Ixogamer commented on plugins/AuctionMaster/auctions_manager.yml
> +auction-created-message: '&aTu puja fue creada!'
```suggestion
auction-created-message: '&a¡Tu subasta fue creada!'
```

2021-07-08 02:54 UTC, Ixogamer commented
Necesito revisar los archivos más a fondo. Tenemos una buena base.

2021-07-08 05:45 UTC, chuske7 commented
Ok si quieres todo eso lo puedo cambiar yo sin problema

El jue., 8 jul. 2021 1:56, Ixo ***@***.***> escribió:

> Está bien por lo que he visto, pero todavía no voy a mergear hasta que lo
> revise más a fondo
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Ixogamer/ipxdevserver/pull/12#issuecomment-876010565>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AURU3II3RE7NCJX6OQEJ7WDTWTSUFANCNFSM477FMPMA>
> .
>

2021-07-08 05:47 UTC, chuske7 commented
Ok

El jue., 8 jul. 2021 4:53, Ixo ***@***.***> escribió:

> *@Ixogamer* requested changes on this pull request.
>
> Por favor, no vuelvas a usar traductor para palabras solas :c, y pon
> primero los archivos de configuración en inglés, y luego en español (Para
> poder conseguir contexto)
> ------------------------------
>
> In plugins/AuctionMaster/auctions_manager.yml
> <https://github.com/Ixogamer/ipxdevserver/pull/12#discussion_r665826071>:
>
> > +    - '&7Acaba en: &e%duration%'
>
> +    - ''
>
> +    - '&eClick para inspeccionar!'
>
> +  #The lore for items with bids on them
>
> +  #Use %display-name-seller% for display name of the seller
>
> +  #Use %bids% for the amount of bids
>
> +  #Use %top-bid% for the top bid
>
> +  #Use %top-bid-player% for the top bid player
>
> +  #Use %duration% for auction duration
>
> +  auction-item-with-bids:
>
> +    - '&8&m---------------------'
>
> +    - '&7Vendedor: %display-name-seller%'
>
> +    - '&7Pujas: &a%bids% pujas'
>
> +    - ''
>
> +    - '&7Mejor oferta: &6%top-bid% monedas'
>
> +    - '&7Mejor ofertador: %top-bid-player%'
>
>
> ⬇️ Suggested change
>
> -    - '&7Mejor ofertador: %top-bid-player%'
>
> +    - '&7Mejor pujador: %top-bid-player%'
>
>
> ------------------------------
>
> In plugins/AuctionMaster/auctions_manager.yml
> <https://github.com/Ixogamer/ipxdevserver/pull/12#discussion_r665826819>:
>
> > +    - ''
>
> +    - '&7Acaba en: &e%duration%'
>
> +    - ''
>
> +    - '&eClick para inspeccionar!'
>
> +  #The lore for items with bids on them
>
> +  #Use %display-name-seller% for display name of the seller
>
> +  #Use %bids% for the amount of bids
>
> +  #Use %top-bid% for the top bid
>
> +  #Use %top-bid-player% for the top bid player
>
> +  #Use %duration% for auction duration
>
> +  auction-item-with-bids:
>
> +    - '&8&m---------------------'
>
> +    - '&7Vendedor: %display-name-seller%'
>
> +    - '&7Pujas: &a%bids% pujas'
>
> +    - ''
>
> +    - '&7Mejor oferta: &6%top-bid% monedas'
>
>
> Quizás puja? Ah, y en vez de monedas, creo que ahí no debería haber nada,
> ya que el plugin de economía le debería añadir un Ξ (Símbolo de la economía
> de IpxCraft). Lo compruebo luego.
> ------------------------------
>
> In plugins/AuctionMaster/auctions_manager.yml
> <https://github.com/Ixogamer/ipxdevserver/pull/12#discussion_r665827087>:
>
> > +    - '&7Mejor oferta: &6%top-bid% monedas'
>
> +    - '&7Mejor ofertador: %top-bid-player%'
>
>
> Lo mismo de líneas 27 y 28
> ------------------------------
>
> In plugins/AuctionMaster/auctions_manager.yml
> <https://github.com/Ixogamer/ipxdevserver/pull/12#discussion_r665827434>:
>
> > +    - '&7Acaba en: &e%duration%'
>
> +    - ''
>
> +    - '&eClick para inspeccionar!'
>
> +  #Use %display-name-seller% for display name of the seller
>
> +  #Use %bids% for the amount of bids
>
> +  #Use %top-bid% for the top bid
>
> +  #Use %top-bid-player% for the top bid player
>
> +  auction-item-ended:
>
> +    - '&8&m---------------------'
>
> +    - '&7Vendedor: %display-name-seller%'
>
> +    - '&7Pujas: &a%bids% bids'
>
> +    - ''
>
> +    - '&7Mejor oferta: &6%top-bid% monedas'
>
> +    - '&7Mejor ofertador: %top-bid-player%'
>
> +    - ''
>
> +    - '&7Estado: &aEnded!'
>
>
> ⬇️ Suggested change
>
> -    - '&7Estado: &aEnded!'
>
> +    - '&7Estado: &aAcabado!'
>
>
> ------------------------------
>
> In plugins/AuctionMaster/auctions_manager.yml
> <https://github.com/Ixogamer/ipxdevserver/pull/12#discussion_r665827755>:
>
> > +  highest-bid: 'Oferta mas alta'
>
> +  lowest-bid: 'Oferta mas baja'
>
>
> ⬇️ Suggested change
>
> -  highest-bid: 'Oferta mas alta'
>
> -  lowest-bid: 'Oferta mas baja'
>
> +  highest-bid: 'Puja mas alta'
>
> +  lowest-bid: 'Puja mas baja'
>
>
> ------------------------------
>
> In plugins/AuctionMaster/auctions_manager.yml
> <https://github.com/Ixogamer/ipxdevserver/pull/12#discussion_r665828023>:
>
> > +    - '&7Vendedor: %display-name-seller%'
>
> +    - '&7La puja empieza en: &6%starting-bid% monedas'
>
> +    - ''
>
> +    - '&7Estado: &cCaducado!'
>
> +    - ''
>
> +    - '&eClick para inspeccionar!'
>
> +
>
> +sort-auction-item: '154'
>
> +sort-auction-item-name: '&aClasificar'
>
> +#The lore is dynamic so you can only edit
>
> +#the names of the sortings
>
> +sort-auction-item-sorting:
>
> +  highest-bid: 'Oferta mas alta'
>
> +  lowest-bid: 'Oferta mas baja'
>
> +  ending-soon: 'Acabando en poco'
>
> +  most-bids: 'Mayoría de las ofertas'
>
>
> Creo que esto no está bien, pero no sé el contexto. Quizás debería ser
> ⬇️ Suggested change
>
> -  most-bids: 'Mayoría de las ofertas'
>
> +  most-bids: 'Más pujas'
>
>
> ------------------------------
>
> In plugins/AuctionMaster/auctions_manager.yml
> <https://github.com/Ixogamer/ipxdevserver/pull/12#discussion_r665828384>:
>
> > +create-menu-name: '&8creador de pujas'
>
> +manage-own-auctions-menu-name: '&8tu gestor de acciones'
>
>
> ¿Deberían de ser mayúsculas? Ah, y "auctions" es "subastas"
> ⬇️ Suggested change
>
> -create-menu-name: '&8creador de pujas'
>
> -manage-own-auctions-menu-name: '&8tu gestor de acciones'
>
> +create-menu-name: '&8Creador de pujas'
>
> +manage-own-auctions-menu-name: '&8Tu gestor de subastas'
>
>
> ------------------------------
>
> In plugins/AuctionMaster/auctions_manager.yml
> <https://github.com/Ixogamer/ipxdevserver/pull/12#discussion_r665828527>:
>
> > +#The message displayed on the sign when searching for an auction
>
> +#There are only 3 rows because the first is where the user writes
>
> +search-sign-message:
>
> +  - '^^^^^^^^^^^^^^^'
>
> +  - 'Escriba su'
>
> +  - 'busqueda'
>
> +
>
> +create-menu-name: '&8creador de pujas'
>
> +manage-own-auctions-menu-name: '&8tu gestor de acciones'
>
> +manage-menu-item: '418'
>
> +manage-menu-item-name: '&aGestionar subastas'
>
> +manage-menu-item-lore:
>
> +  #This lore is displayed when the player has no own auction
>
> +  manage-no-own-auctions:
>
> +    - '&7Pon tus propios articulos en'
>
> +    - '&7pujas para otros jugadores'
>
>
> ⬇️ Suggested change
>
> -    - '&7pujas para otros jugadores'
>
> +    - '&7subastas para otros jugadores'
>
>
> ------------------------------
>
> In plugins/AuctionMaster/auctions_manager.yml
> <https://github.com/Ixogamer/ipxdevserver/pull/12#discussion_r665828665>:
>
> > +  - '^^^^^^^^^^^^^^^'
>
> +  - 'Escriba su'
>
> +  - 'busqueda'
>
> +
>
> +create-menu-name: '&8creador de pujas'
>
> +manage-own-auctions-menu-name: '&8tu gestor de acciones'
>
> +manage-menu-item: '418'
>
> +manage-menu-item-name: '&aGestionar subastas'
>
> +manage-menu-item-lore:
>
> +  #This lore is displayed when the player has no own auction
>
> +  manage-no-own-auctions:
>
> +    - '&7Pon tus propios articulos en'
>
> +    - '&7pujas para otros jugadores'
>
> +    - '&7para comprar.'
>
> +    - ''
>
> +    - '&eClick para convertirte en rico!'
>
>
> No sé si este contexto está bien, tengo que comprobarlo.
> ------------------------------
>
> In plugins/AuctionMaster/auctions_manager.yml
> <https://github.com/Ixogamer/ipxdevserver/pull/12#discussion_r665829348>:
>
> > +    - '&7Tu propia &e%auctions% puja &7in'
>
> +    - '&7progreso que termino'
>
> +    - '&7recientemente.'
>
> +    - ''
>
> +    - '&7Tus pujas tienen &a%bids% ofertas'
>
> +    - '&7totalizando &6%coins% monedas&7.'
>
> +    - ''
>
>
> Esto está mal traducido.
> ------------------------------
>
> In plugins/AuctionMaster/auctions_manager.yml
> <https://github.com/Ixogamer/ipxdevserver/pull/12#discussion_r665829650>:
>
> > +    - '&eHaga click para reclamar!'
>
> +  own-bids:
>
> +    - '&8Pujas acabadas'
>
> +    - ''
>
> +    - '&7Hay &e%auctions% &7Pujas acabadas'
>
> +    - '&7en la cual ofreces.'
>
> +    - ''
>
> +    - '&7Tienes &6%coins% &7monedas para'
>
> +    - '&7reclamar de subastas perdidas y'
>
> +    - '&e%items% &7articulos de pujas ganadas.'
>
> +    - ''
>
> +    - '&eClick para reclamar!'
>
> +
>
> +#The message sent when the player has a full inventory but tries to claim an item
>
> +no [...]

2021-07-10 06:22 UTC, Ixogamer requested changes

2021-07-10 06:22 UTC, Ixogamer commented on plugins/AuctionMaster/bids_related.yml
> +    - '&7Se el primero enpujar!'
```suggestion
    - '&7Se el primero en pujar!'
```

2021-07-10 06:22 UTC, Ixogamer commented on plugins/AuctionMaster/bids_related.yml
> +bids-menu-name: '&8Vista de subasta'
Quizás esto está mal, miraremos el contexto en la última fase de desarrollo.

2021-07-10 06:22 UTC, Ixogamer commented on plugins/AuctionMaster/bids_related.yml
> +too-late-to-open-now: '&cEs muy tarde para habrir esto ahora!'
```suggestion
too-late-to-open-now: '&c¡Es muy tarde para abrir esto ahora!'
```

2021-07-10 06:22 UTC, Ixogamer commented on plugins/AuctionMaster/bids_related.yml
> +    - '&7Puja: &6%bid-amount% monedas'
```suggestion
    - '&7Puja: &6%bid-amount%'
```

2021-07-10 06:22 UTC, Ixogamer commented on plugins/AuctionMaster/bids_related.yml
> +    - '&7Nueva oferta: &6%bid-amount% monedas'
```suggestion
    - '&7Nueva oferta: &6%bid-amount%'
```

2021-07-10 06:22 UTC, Ixogamer commented on plugins/AuctionMaster/bids_related.yml
> +    - '&7Previous Bid: &e%previous-bid% monedas'
```suggestion
    - '&7Nueva oferta: &6%bid-amount%'
    - '&7Previous Bid: &e%previous-bid%'
```

2021-07-10 06:22 UTC, Ixogamer commented on plugins/AuctionMaster/bids_related.yml
> +    - '&7Tu pagas: &6%coins-to-pay% monedas'
```suggestion
    - '&7Tu pagas: &6%coins-to-pay%'
```

2021-07-10 06:22 UTC, Ixogamer commented on plugins/AuctionMaster/bids_related.yml
> +    - '&7Tienes &6%coins% monedas'
```suggestion
    - '&7Tienes &6%coins%'
```

2021-07-10 06:22 UTC, Ixogamer commented on plugins/AuctionMaster/bids_related.yml
> +edit-bid-item-name: '&fImporte de la oferta: &6%current-bid% monedas'
```suggestion
edit-bid-item-name: '&fImporte de la oferta: &6%current-bid%'
```

2021-07-10 06:22 UTC, Ixogamer commented on plugins/AuctionMaster/bids_related.yml
> +  - '&6%minimum-bid% monedas &7para ponerte en la cima'
```suggestion
  - '&6%minimum-bid% &7para ponerte en la cima'
```

2021-07-10 06:22 UTC, Ixogamer commented on plugins/AuctionMaster/bids_related.yml
> +  - '&7reclamar tus monedas de vuelta.'
```suggestion
  - '&7reclamar tu dinero de vuelta.'
```

2021-07-10 06:22 UTC, Ixogamer commented on plugins/AuctionMaster/bids_related.yml
> +bid-message: '&6[Auction] %bidder% &fponer una oferta de &6%bid-amount% monedas &fen tu %bid-item%&f!'
```suggestion
bid-message: '&6[Auction] %bidder% &fponer una oferta de &6%bid-amount% &fen tu %bid-item%&f!'
```

2021-07-10 06:22 UTC, Ixogamer commented on plugins/AuctionMaster/bids_related.yml
> +own-auction-message: '&aEsta es tu propia puja!'
```suggestion
own-auction-message: '&a¡Esta es tu propia subasta!'
```

2021-07-11 04:03 UTC, Shxilan requested changes
Sobre todo he cambiado signos de puntuación además de alguna que otra falta comprensiva

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/bids_related.yml
> +placed-bid-message: '&aSu oferta se realizó con éxito!'
```suggestion
placed-bid-message: '&a¡Su oferta se realizó con éxito!'
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/bids_related.yml
> +  - '&cRabriendo el menu...'
```suggestion
  - '&cReabriendo el menu...'
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/buyItNow.yml
> +    - '&eClick para editar!'
```suggestion
    - '&e¡Click para editar!'
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/buyItNow.yml
> +      - '&eClick para cambiar!'
```suggestion
      - '&e¡Click para cambiar!'
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/buyItNow.yml
> +      - '&7Pujas de CPA son simples.'
```suggestion
      - '&7Subastas de CPA son simples.'
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/buyItNow.yml
> +      - '&7Estableze un precio, entonces un jugador puede'
```suggestion
      - '&7Establece un precio, entonces un jugador puede'
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/buyItNow.yml
> +      - '&eClick para cambiar!'
```suggestion
      - '&e¡Click para cambiar!'
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/buyItNow.yml
> +    - '&eClick para inspeccionar!'
```suggestion
    - '&e¡Click para inspeccionar!'
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/buyItNow.yml
> +    - '&7Estado: &cCaducado!'
```suggestion
    - '&7Estado: &c¡Caducado!'
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/buyItNow.yml
> +    - '&eClick para inspeccionar!'
```suggestion
    - '&e¡Click para inspeccionar!'
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/buyItNow.yml
> +    - '&eClick para inspeccionar!'
```suggestion
    - '&e¡Click para inspeccionar!'
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/buyItNow.yml
> +  click-to-switch: '&eClick para cambiar el filtro!'
```suggestion
  click-to-switch: '&e¡Click para cambiar el filtro!'
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/buyItNow.yml
> +      - '&7Precio: &6%price% monedas'
```suggestion
      - '&7Precio: &6%price%'
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/buyItNow.yml
> +      - '&eClick para comprar!'
```suggestion
      - '&e¡Click para comprar!'
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/buyItNow.yml
> +      - '&7Precio: &6%price% monedas'
```suggestion
      - '&7Precio: &6%price%'
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/buyItNow.yml
> +      - '&cNo puedes pagar la oferta!'
```suggestion
      - '&c¡No puedes pagar la oferta!'
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/config.yml
> +end-own-auction-name: '&aTerminar puja ahora'
```suggestion
end-own-auction-name: '&aTerminar la subasta ahora'
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/config.yml
> +  - '&7Terminar esta puja'
```suggestion
  - '&7Terminar esta subasta'
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/config.yml
> +end-own-auction-message: '&aTu puja se ha acabado!'
```suggestion
end-own-auction-message: '&a¡Tu puja se ha acabado!'
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/config.yml
> +end-own-auction-no-money-message: '&cNo tienes suficientes monedas para acabar esta puja!.'
```suggestion
end-own-auction-no-money-message: '&c¡No tienes suficientes monedas para acabar esta puja!.'
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/config.yml
> +  - '&fcategoria en el'
```suggestion
  - '&fcategoría en el'
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/config.yml
> +can-not-outbid-message: '&cNo puedes superar tu propia puja!'
```suggestion
can-not-outbid-message: '&c¡No puedes superar tu propia subasta!'
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/config.yml
> +category-no-browsing: '&eHaz click para ver los items!'
```suggestion
category-no-browsing: '&e¡Haz click para ver los items!'
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/config.yml
> +category-browsing: '&aCurrently browsing!'
```suggestion
category-browsing: '&a¡Currently browsing!'
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/config.yml
> +  - '&7Ir atras al menu de pujas.'
```suggestion
  - '&7Ir atras al menu de subastas.'
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/config.yml
> +  - '&7la pagina de antes.'
```suggestion
  - '&7la página de antes.'
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/config.yml
> +  - '&7la siguiente pagina.'
```suggestion
  - '&7la siguiente página.'
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/config.yml
> +starting-menu-name: '&8Menu de pujas'
```suggestion
starting-menu-name: '&8Menu de subastas'
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/config.yml
> +  - '&7jugadores alrrededor del server!'
```suggestion
  - '&7jugadores alrededor del server'
```
No veo necesario los signos de exclamación

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/config.yml
> +  - '&7Items los items ofrecidos aqui son para'
¿Por qué repites dos veces items?

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/config.yml
> +  - '&eClic para navegar!'
```suggestion
  - '&e¡Clic para navegar!'
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/config.yml
> +    - '&eClick para ver!'
```suggestion
    - '&e¡Click para ver!'
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/config.yml
> +    - '&7Haz ofertas por artículos y haz click '
```suggestion
    - '&7¡Haz ofertas por artículos y haz click '
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/config.yml
> +    - '&cNo tienes ninguna oferta!'
```suggestion
    - '&c¡No tienes ninguna oferta!'
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/config.yml
> +no-bids-message: '&cNo tienes ninguna oferta!'
```suggestion
no-bids-message: '&c¡No tienes ninguna oferta!'
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/config.yml
> +  - '&7Aquí vienen los artículos y'
```suggestion
  - '&7¡Aquí vienen los artículos y'
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/config.yml
> +delivery-have-message: '&aTienes entregas!'
```suggestion
delivery-have-message: '&a¡Tienes entregas!'
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/config.yml
> +    - '&7Tienes una entrega!'
```suggestion
    - '&7¡Tienes una entrega!'
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/config.yml
> +    - '&aClick para reclamar!'
```suggestion
    - '&a¡Click para reclamar!'
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/config.yml
> +no-delivery-to-claim: '&cNo tienes ninguna entrega que reclamar!'
```suggestion
no-delivery-to-claim: '&c¡No tienes ninguna entrega que reclamar!'
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/config.yml
> +delivery-alert-join-message: '&6[Auction] &fTienes entregas no reclamadas!'
```suggestion
delivery-alert-join-message: '&6[Auction] &f¡Tienes entregas no reclamadas!'
```
Creo que sería mejor poniendo "¡X entregas no reclamadas!"

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/config.yml
> +delivery-got-message: '&6[Auction] &fHas recibido &6%coins% coins &fand &e%item-count% items&f!'
```suggestion
delivery-got-message: '&6[Auction] &f¡Has recibido &6%coins% coins &fand &e%item-count% items&f!'
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/config.yml
> +  - '&c/auctionhouse &8- &7Habrir menu de pujas'
```suggestion
  - '&c/auctionhouse &8- &7Abrir menú de subastas'
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/config.yml
> +  - '&c/ah <player name> &8- &7Habrir una puja de un jugador'
```suggestion
  - '&c/ah <player name> &8- &7Abrir una subasta de un jugador'
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/config.yml
> +  - '&4/ahadmin &8- &7Habrir menu de admin'
```suggestion
  - '&4/ahadmin &8- &7Abrir menú de administrador'
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/config.yml
> +  - '&c/ah delivery &8- &7Habrir menu de entregas'
```suggestion
  - '&c/ah delivery &8- &7Abrir menú de entregas'
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/config.yml
> +auction-no-permission: '&cNo tienes el permiso para habrir el menu!'
```suggestion
auction-no-permission: '&c¡No tienes el permiso para abrir el menú!'
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/config.yml
> +auction-command-deny: '&cNo tienes permisos suficientes para utilizar este comando!'
```suggestion
auction-command-deny: '&c¡No tienes permisos suficientes para utilizar este comando!'
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/config.yml
> +admin-perks-deny: '&cNo puedes usar comandos de admins!'
```suggestion
admin-perks-deny: '&c¡No puedes usar comandos de administrador!'
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/config.yml
> +auction-command-missing: '&cDeberias usar /ah <nombre del jugador>!'
```suggestion
auction-command-missing: '&c¡Deberías usar /ah <nombre del jugador>!'
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/config.yml
> +  line-1: '&6Maestro de pujas'
```suggestion
  line-1: '&6Maestro de subastas'
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/config.yml
> +no-auctions-message: '&eEste jugador no tiene ninguna puja activa.'
```suggestion
no-auctions-message: '&eEste jugador no tiene ninguna subasta activa.'
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/menus/others.yml
> +  - '&8Categoria'
```suggestion
  - '&8Categoría'
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/menus/others.yml
> +  - '&7en otras categorias.'
```suggestion
  - '&7en otras categorías.'
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/menus/tools.yml
> +  - '&8Categoria'
```suggestion
  - '&8Categoría'
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/menus/weapons.yml
> +  - '&8Categoria'
```suggestion
  - '&8Categoría'
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/menus/consumables.yml
> +  - '&8Categoria'
```suggestion
  - '&8Categoría'
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/menus/blocks.yml
> +  - '&8Categoria'
```suggestion
  - '&8Categoría'
```

2021-07-11 04:03 UTC, Shxilan commented on plugins/AuctionMaster/menus/armor.yml
> +  - '&8Categoria'
```suggestion
  - '&8Categoría'
```

2021-07-12 12:16 UTC, Shxilan requested changes
Solo tuve que poner algunas mayúsculas por todo lo demás está correcto desde mi punto de vista

2021-07-12 12:16 UTC, Shxilan commented on plugins/AuctionMaster/menus/consumables.yml
> +  - '&8■ &7comida'
```suggestion
  - '&8■ &7Comida'
```

2021-07-12 12:16 UTC, Shxilan commented on plugins/AuctionMaster/menus/others.yml
> +  - '&7Pujable y no'
```suggestion
  - '&7subastable y no'
```

2021-07-15 04:31 UTC, Ixogamer requested changes
Creo que ya está Gucci

2021-07-15 04:31 UTC, Ixogamer commented on plugins/AuctionMaster/buyItNow.yml
> +    - '&7Precio: &6%price% coins'
```suggestion
    - '&7Precio: &6%price%'
```

2021-07-15 04:31 UTC, Ixogamer commented on plugins/AuctionMaster/buyItNow.yml
> +bought-item-message: '&eHas comprado &f%item% &ede %seller-display-name% &epor &6%coins% Monedas&e!'
```suggestion
bought-item-message: '&eHas comprado &f%item% &ede %seller-display-name% &epor &6%coins%&e!'
```

2021-07-15 04:31 UTC, Ixogamer commented on plugins/AuctionMaster/buyItNow.yml
> +bought-seller-notification: '&6[Auction] %bidder-display-name% &fha comprado tu  %item%&f por &6%price% monedas&f!'
```suggestion
bought-seller-notification: '&6[Auction] %bidder-display-name% &fha comprado tu  %item%&f por &6%price%&f!'
```

2021-07-15 04:31 UTC, Ixogamer commented on plugins/AuctionMaster/config.yml
> +end-own-auction-message: '&aTu puja se ha acabado!'
```suggestion
end-own-auction-message: '&a¡Tu subasta se ha acabado!'
```

2021-07-15 04:31 UTC, Ixogamer commented on plugins/AuctionMaster/config.yml
> +end-own-auction-no-money-message: '&cNo tienes suficientes monedas para acabar esta puja!.'
```suggestion
end-own-auction-no-money-message: '&c¡No tienes suficientes monedas para acabar esta subasta!.'
```

2021-07-15 04:31 UTC, Ixogamer commented on plugins/AuctionMaster/config.yml
> +broadcast-new-auction-message: '&6[Auctions] %seller-display-name% &fha creado una puja para %item-display-name%&f! &e&lCLICK &e&lTO &e&lVIEW'
```suggestion
broadcast-new-auction-message: '&6[Auctions] %seller-display-name% &fha creado una subasta para %item-display-name%&f! &e&lCLICK &e&lPARA &e&lVER'
```

2021-07-15 04:31 UTC, Ixogamer commented on plugins/AuctionMaster/config.yml
> +broadcast-new-auction: false
```suggestion
broadcast-new-auction: true
```

2021-07-15 04:31 UTC, Ixogamer commented on plugins/AuctionMaster/config.yml
> +  - '&7Ir atras al menu de pujas.'
```suggestion
  - '&7Ir atrás al menu de subastas.'
```

2021-07-15 04:31 UTC, Ixogamer commented on plugins/AuctionMaster/config.yml
> +previous-page-item-name: '&aPage %page-number%'
```suggestion
previous-page-item-name: '&aPágina %page-number%'
```

2021-07-15 04:31 UTC, Ixogamer commented on plugins/AuctionMaster/config.yml
> +next-page-item-name: '&aPage %page-number%'
```suggestion
next-page-item-name: '&aPágina %page-number%'
```

2021-07-15 04:31 UTC, Ixogamer commented on plugins/AuctionMaster/config.yml
> +  - '&7Items los items ofrecidos aqui son para'
```suggestion
  - '&7Los items ofrecidos aqui son para'
```

I guess?

2021-07-15 04:31 UTC, Ixogamer commented on plugins/AuctionMaster/config.yml
> +    - '&7apuestas pendientes.'
???

2021-07-15 04:31 UTC, Ixogamer commented on plugins/AuctionMaster/config.yml
> +    - '&7 - &6%coins% monedas'
```suggestion
    - '&7 - &6%coins%'
```

2021-07-15 04:31 UTC, Ixogamer commented on plugins/AuctionMaster/config.yml
> +delivery-got-message: '&6[Auction] &fHas recibido &6%coins% coins &fand &e%item-count% items&f!'
```suggestion
delivery-got-message: '&6[Auction] &f¡Has recibido &6%coins% &fy &e%item-count% items&f!'
```

2021-07-15 04:31 UTC, Ixogamer commented on plugins/AuctionMaster/config.yml
> +player-auction-menu-name: 'La puja de: &8%player%'
```suggestion
player-auction-menu-name: 'La subasta de: &8%player%'
```

2021-07-15 04:33 UTC, Ixogamer requested changes

2021-07-15 04:33 UTC, Ixogamer commented on plugins/AuctionMaster/auctions_manager.yml
> +    - '&7Mejor oferta: &6%top-bid% monedas'
```suggestion
    - '&7Mejor oferta: &6%top-bid%'
```

2021-07-15 04:40 UTC, Ixogamer commented on plugins/AuctionMaster/auctions_manager.yml
> +    - '&7Mejor oferta: &6%top-bid% monedas'
```suggestion
    - '&7Mejor oferta: &6%top-bid%'
```

2021-07-15 04:47 UTC, Ixogamer commented
Okay, ya debería de estar esto. Perfecto, voy a comprobarlo en mi test server y mirar si funciona.

2021-07-15 04:48 UTC, Ixogamer approved these changes

2021-07-15 04:48 UTC, merged